### ISSUE TITLE
Transporter II Uranium Consumption Calculation

### ISSUE THREAD

**Issue by Jarunik** [Jarunik/nc-client#130]
famigliacurione: For some reason, the Fuel Consumption seems wrong when I send out my Transporter II ships. It only happens when I send Transporter IIs alone. The transaction does not subtract this amount, however. :nerd:

https://media.discordapp.net/attachments/591635802174259201/651397300127662090/trans2fuel.JPG

**Comment by famigliacurione** [comment]
Now that I am sending out many more Transporter IIs at a time, the Fuel Consumption error prevents the transaction from being sent because the Uranium required is too high.

**Comment by Jarunik** [comment]
Can't reproduce the problem. Calculation seems to be fine. Will need examples of wrong consumption calculations.

**Comment by famigliacurione** [comment]
Am also unable to reproduce problem today. I suppose that's a good thing. I tried to do exactly what I did yesterday, but the calculations were correct. My past attempts involved a copy and paste of the coordinates to be attacked, but I repeated this today and the problem did not occur. I guess it's a closed issue for now. I'll report if it happens again, with more detail.
