### ISSUE TITLE
Uranium Fuel Consumption Not Showing

### ISSUE THREAD

**Issue by famigliacurione** [Jarunik/nc-client#71]
When sending Missions, the **Uranium Fuel** field remains at 0.00 resulting in transactions being sent to the blockchain, but in-game the Missions are not sent. I have on more than one occasion, sent an Explorer II long range, without noticing that there was not enough Uranium. As a result, I resend the Mission thinking that the transaction didn't go through.

**Comment by Jarunik** [comment]
fixed it.
